apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "fronend.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIp
  ports:
    - targetPort: http
      protocol: TCP
      name: http
      port: 80